project:
  type: website
  output-dir: docs

website:
  title: "Mini-Cursos - Explorando finanças com R "
  navbar:
    left:
      - href: index.qmd
        text: Início
        icon: bi-house
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



