---
title: "Mini-curso de finanças com R"
---

# Bem-vindo(a)!!

Neste curso você aprenderá a utilizar o R para análise de dados financeiros. O curso terá duração de 3 horas e será dividido em 3 partes:

1.  Importar os preços dos ativos da internet em arquivos .csv ou .xls

2.  Transformar os preços diários em mensais.

3.  Obter os retornos mensais.

4.  Visualizar os retornos mensais.

5.  Calcular o retorno do portifólio utilizando os retornos mensais e pesos.

6.  Visualizar o retorno do portifólio.

## Pré-requisitos

Esperamos que você já tenha tido contato com R e Quarto. 
Um computador com acesso à internet para acessar o ambiente de desenvolvimento Posit Cloud ou baixar o repositorio do curso.

## Preparação

Para se preparar para o curso, você pode baixar o repositório do curso no link abaixo: 

[Repositório no GitHub](https://github.com/nextmarte/MiniCursoFinSER)

[Link para o ambiente de desenvolvimento Posit Cloud](https://cloud.positivestudio.com/)

## Instrutores

- Marcus Ramalho
- Ariel Levy